apiVersion: fedlearner.k8s.io/v1alpha1
kind: FLApp
metadata:
  name: normal
  namespace: follower
spec:
  flReplicaSpecs:
    Master:
      pair: true
      replicas: 1
      template:
        spec:
          restartPolicy: Never # required
          containers:
            - env:
              - name: APPLICATION_ID
                value: normal
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              image: nicolaka/netshoot
              imagePullPolicy: IfNotPresent
              restartPolicy: Never # required
              name: tensorflow # default
              ports:
                - containerPort: 50051
                  name: flapp-port # default
              resources:
                limits:
                  cpu: 1000m
                  memory: 1Gi
                requests:
                  cpu: 1000m
                  memory: 1Gi
              command: ["/bin/sleep"]
              args: ["3m"]
    PS:
      pair: false
      replicas: 0
      template:
        spec:
          restartPolicy: Never # required
          containers:
            - env:
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              image: nicolaka/netshoot
              imagePullPolicy: IfNotPresent
              restartPolicy: Never # required
              name: tensorflow # default
              ports:
                - containerPort: 50051
                  name: flapp-port # default
              resources:
                limits:
                  cpu: 1000m
                  memory: 500Mi
                requests:
                  cpu: 1000m
                  memory: 500Mi
              command: ["/bin/sleep"]
              args: ["3m"]
    Worker:
      pair: true
      replicas: 2
      chiefResources:
        limits:
          cpu: 2000m
          memory: 1000Mi
        requests:
          cpu: 2000m
          memory: 1000Mi
      template:
        spec:
          restartPolicy: Never # required
          containers:
            - env:
              - name: APPLICATION_ID
                value: normal
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              image: nicolaka/netshoot
              imagePullPolicy: IfNotPresent
              name: tensorflow # default
              ports:
                - containerPort: 50051
                  name: flapp-port # default
              resources:
                limits:
                  cpu: 1000m
                  memory: 500Mi
                requests:
                  cpu: 1000m
                  memory: 500Mi
              command: ["/bin/sleep"]
              args: ["3m"]
  role: Follower
  peerSpecs:
    Leader:
      peerURL: flapp-operator.leader.svc.cluster.local:8100

