{{- if .Values.ingress.enabled -}}
{{- $configurationSnippet := .Files.Get "configuration-snippet.txt" -}}
{{- $serverSnippet := .Files.Get "server-snippet.txt" -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: fedlearner-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fedlearner-add-on.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if not (empty $configurationSnippet) }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
{{ $configurationSnippet | indent 6 }}
    {{- end }}
    {{- if not (empty $serverSnippet) }}
    nginx.ingress.kubernetes.io/server-snippet: |
{{ $serverSnippet | indent 6 }}
    {{- end }}
  {{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fedlearner-proxy
            port:
              number: {{ .Values.ingress.port }}
{{- else -}}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: fedlearner-proxy
              servicePort: {{ .Values.ingress.port }}
{{- end }}

{{- end }}
