name: Release Fedlearner

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Short Commit Sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: fedlearner
          password: "${{ secrets.DOCKER_REGISTRY }}"
          image_name: fedlearner
          image_tag: ${{ steps.vars.outputs.sha_short }}
          context: ./
