name: Tag Kubernetes Operator

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Short Commit Sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: fedlearner
          password: "${{ secrets.DOCKER_REGISTRY }}"
          image_name: fedlearner/fedlearner-operator
          image_tag: ${{ github.event.release.tag_name }}
          context: ./deploy/kubernetes_operator
          build_extra_args: --build-arg=WHAT=cmd/operator/main.go
